name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  rust:
    uses: rowanjove/.github/.github/workflows/rust-ci.yml@main
    with:
      working-directory: src-tauri

  node:
    uses: rowanjove/.github/.github/workflows/node-ci.yml@main
